### ISSUE TITLE
Problème fichier URL vietnamien

### ISSUE THREAD

**Issue by YoannDupont** [Amina-Bou/PPE-groupe#1]
Bonjour,

Votre [fichier d'URL vietnamien](https://github.com/Amina-Bou/PPE-groupe/blob/main/url/url-Vietnamien.md) a quelques soucis :

- il y a des lignes vides, pas très grave, mais il faudrait les retirer
- il y a du texte (parfois des lignes) qui ne représente pas des URL, exemple : `(Cmt prévenir les grèves au VN)` qui ne devrait pas être là

Si vous voulez mettre des commentaires sur vos URL, il faut le faire dans un autre fichier. Les fichiers d'URL ne doivent contenir que des URL.

**Comment by tsngu** [comment]
Bonsoir,
C'est modifié ! 
Merci beaucoup

**Comment by YoannDupont** [comment]
Le fichier me semble bon, je clos l'issue.
